version: "3.9"

services:
  test-runner:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src
    volumes:
      - .:/src
      - ./coverage:/src/TestResults
    command: /bin/bash -c "\
      dotnet restore src/TaskManagement.API/TaskManagement.API.csproj && \
      dotnet test tests/TaskManagement.Tests.Unit/TaskManagement.Tests.Unit.csproj --collect:\"XPlat Code Coverage\" --results-directory /src/TestResults && \
      dotnet tool install -g dotnet-reportgenerator-globaltool --version 5.1.10 && \
      /root/.dotnet/tools/reportgenerator -reports:/src/TestResults/**/*.cobertura.xml -targetdir:/src/TestResults/report -reporttypes:Html"
