version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: src/TaskManagement.API/Dockerfile
    ports:
      - "5000:8080"
    networks:
      - taskmanagement
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/wait-for.sh", "dotnet", "TaskManagement.API.dll"]
    volumes:
      - .:/src  # Mapeia o código para poder editar/rodar comandos manualmente dentro do container

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmanagement
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - taskmanagement
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db_data:

networks:
  taskmanagement:
    driver: bridge
